In [6]:
import pandas as pd
from pathlib import Path

mutation_path = Path("../data/raw/gbm_tcga_pan_can_atlas_2018_mutations.txt")

print("Exists:", mutation_path.exists())

Exists: True

In [7]:
mutations = pd.read_csv(
    mutation_path,
    sep="\t",
    comment="#",
    low_memory=False
)

print("Rows:", mutations.shape[0])
print("Columns:", mutations.shape[1])

Rows: 68802
Columns: 114

In [8]:
mutations.columns.tolist()

['Hugo_Symbol',
 'Entrez_Gene_Id',
 'Center',
 'NCBI_Build',
 'Chromosome',
 'Start_Position',
 'End_Position',
 'Strand',
 'Consequence',
 'Variant_Classification',
 'Variant_Type',
 'Reference_Allele',
 'Tumor_Seq_Allele1',
 'Tumor_Seq_Allele2',
 'dbSNP_RS',
 'dbSNP_Val_Status',
 'Tumor_Sample_Barcode',
 'Matched_Norm_Sample_Barcode',
 'Match_Norm_Seq_Allele1',
 'Match_Norm_Seq_Allele2',
 'Tumor_Validation_Allele1',
 'Tumor_Validation_Allele2',
 'Match_Norm_Validation_Allele1',
 'Match_Norm_Validation_Allele2',
 'Verification_Status',
 'Validation_Status',
 'Mutation_Status',
 'Sequencing_Phase',
 'Sequence_Source',
 'Validation_Method',
 'Score',
 'BAM_File',
 'Sequencer',
 't_ref_count',
 't_alt_count',
 'n_ref_count',
 'n_alt_count',
 'HGVSc',
 'HGVSp',
 'HGVSp_Short',
 'Transcript_ID',
 'RefSeq',
 'Protein_position',
 'Codons',
 'Hotspot',
 'AA_MAF',
 'AFR_MAF',
 'ALLELE_NUM',
 'AMR_MAF',
 'ASN_MAF',
 'Allele',
 'Amino_acids',
 'BIOTYPE',
 'CANONICAL',
 'CCDS',
 'CDS_position',
 'CENTERS',
 'CLIN_SIG',
 'CONTEXT',
 'COSMIC',
 'DBVS',
 'DISTANCE',
 'DOMAINS',
 'EAS_MAF',
 'EA_MAF',
 'ENSP',
 'EUR_MAF',
 'EXON',
 'ExAC_AF',
 'ExAC_AF_AFR',
 'ExAC_AF_AMR',
 'ExAC_AF_EAS',
 'ExAC_AF_FIN',
 'ExAC_AF_NFE',
 'ExAC_AF_OTH',
 'ExAC_AF_SAS',
 'Existing_variation',
 'Exon_Number',
 'FILTER',
 'Feature',
 'Feature_type',
 'GENE_PHENO',
 'GMAF',
 'Gene',
 'HGNC_ID',
 'HGVS_OFFSET',
 'HIGH_INF_POS',
 'IMPACT',
 'INTRON',
 'MERGESOURCE',
 'MINIMISED',
 'MOTIF_NAME',
 'MOTIF_POS',
 'MOTIF_SCORE_CHANGE',
 'NCALLERS',
 'PHENO',
 'PICK',
 'PUBMED',
 'PolyPhen',
 'SAS_MAF',
 'SIFT',
 'SOMATIC',
 'SWISSPROT',
 'SYMBOL',
 'SYMBOL_SOURCE',
 'TREMBL',
 'TSL',
 'UNIPARC',
 'VARIANT_CLASS',
 'all_effects',
 'cDNA_position',
 'n_depth',
 't_depth',
 'Annotation_Status']

In [9]:
mutations.head(5)

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,SYMBOL_SOURCE,TREMBL,TSL,UNIPARC,VARIANT_CLASS,all_effects,cDNA_position,n_depth,t_depth,Annotation_Status
0,TACC2,10579.0,.,GRCh37,10,123810032,123810032,+,missense_variant,Missense_Mutation,...,HGNC,.,.,UPI0000246F6B,SNV,"TACC2,missense_variant,p.Thr38Met,ENST00000358...",453,74,43,SUCCESS
1,JAKMIP3,282973.0,.,GRCh37,10,133967449,133967449,+,synonymous_variant,Silent,...,HGNC,.,.,UPI000157482F,SNV,"JAKMIP3,synonymous_variant,p.%3D,ENST000002986...",2307,123,82,SUCCESS
2,PANX3,116337.0,.,GRCh37,11,124489539,124489539,+,missense_variant,Missense_Mutation,...,HGNC,.,.,UPI0000131264,SNV,"PANX3,missense_variant,p.Arg296Gln,ENST0000028...",954,188,217,SUCCESS
3,SPI1,6688.0,.,GRCh37,11,47380512,47380512,+,missense_variant,Missense_Mutation,...,HGNC,.,.,UPI0000D4ECF1,SNV,"SPI1,missense_variant,p.Pro126Thr,ENST00000378...",417,15,12,SUCCESS
4,NAALAD2,10003.0,.,GRCh37,11,89868837,89868837,+,"missense_variant,splice_region_variant",Missense_Mutation,...,HGNC,"E9PJ53_HUMAN,E9PII2_HUMAN",.,UPI0000031A85,SNV,"NAALAD2,missense_variant,p.Arg11Cys,ENST000005...",423,81,70,SUCCESS

In [10]:
print(
    "Unique tumor samples:",
    mutations["Tumor_Sample_Barcode"].nunique()
)

mutations["Tumor_Sample_Barcode"].head(10)

Unique tumor samples: 395

0    TCGA-02-0003-01
1    TCGA-02-0003-01
2    TCGA-02-0003-01
3    TCGA-02-0003-01
4    TCGA-02-0003-01
5    TCGA-02-0003-01
6    TCGA-02-0003-01
7    TCGA-02-0003-01
8    TCGA-02-0003-01
9    TCGA-02-0003-01
Name: Tumor_Sample_Barcode, dtype: object

In [ ]:
mutations[
    [
        "Hugo_Symbol",
        "Variant_Classification",
        "Variant_Type",
        "Tumor_Sample_Barcode",
        "Mutation_Status"
    ]
].head(10)

# one sample can have many mutation rows

,Hugo_Symbol,Variant_Classification,Variant_Type,Tumor_Sample_Barcode,Mutation_Status
0,TACC2,Missense_Mutation,SNP,TCGA-02-0003-01,.
1,JAKMIP3,Silent,SNP,TCGA-02-0003-01,.
2,PANX3,Missense_Mutation,SNP,TCGA-02-0003-01,.
3,SPI1,Missense_Mutation,SNP,TCGA-02-0003-01,.
4,NAALAD2,Missense_Mutation,SNP,TCGA-02-0003-01,.
5,FAT3,Silent,SNP,TCGA-02-0003-01,.
6,MTERFD3,Missense_Mutation,SNP,TCGA-02-0003-01,.
7,BTBD11,Missense_Mutation,SNP,TCGA-02-0003-01,.
8,NOS1,5'UTR,SNP,TCGA-02-0003-01,.
9,SLC2A14,Missense_Mutation,SNP,TCGA-02-0003-01,.

In [12]:
mutations["Mutation_Status"].value_counts(dropna=False)

Mutation_Status
.    68802
Name: count, dtype: int64

In [13]:
clinical_path = Path("../data/processed/gbm_primary_clinical.tsv")

primary_clinical = pd.read_csv(
    clinical_path,
    sep="\t"
)

print("Primary clinical samples:",
      primary_clinical["Sample ID"].nunique())

print("Mutation samples:",
      mutations["Tumor_Sample_Barcode"].nunique())

Primary clinical samples: 585
Mutation samples: 395

In [14]:
primary_sample_ids = set(primary_clinical["Sample ID"])
mutation_sample_ids = set(mutations["Tumor_Sample_Barcode"])

overlap = primary_sample_ids & mutation_sample_ids

print("Samples present in both:", len(overlap))

Samples present in both: 388

In [ ]:
mutation_not_in_primary = mutation_sample_ids - primary_sample_ids

print("Mutation samples not in primary cohort:",
      len(mutation_not_in_primary))

mutation_not_in_primary

# 7 non-primary samples are exactly the same recurrent samples we identified earlier

Mutation samples not in primary cohort: 7

{'TCGA-06-0125-02',
 'TCGA-06-0171-02',
 'TCGA-06-0190-02',
 'TCGA-06-0210-02',
 'TCGA-06-0211-02',
 'TCGA-06-0221-02',
 'TCGA-14-1034-02'}

In [16]:
primary_mutations = mutations[
    mutations["Tumor_Sample_Barcode"].isin(primary_sample_ids)
].copy()

print("Mutation rows before filtering:", mutations.shape[0])
print("Mutation rows after primary filtering:", primary_mutations.shape[0])

print(
    "Unique primary mutation samples:",
    primary_mutations["Tumor_Sample_Barcode"].nunique()
)

Mutation rows before filtering: 68802
Mutation rows after primary filtering: 68161
Unique primary mutation samples: 388

In [17]:
primary_mutations[
    primary_mutations["Tumor_Sample_Barcode"].str.endswith("-02")
]["Tumor_Sample_Barcode"].unique()

array([], dtype=object)

In [18]:
primary_mutations["Variant_Classification"].value_counts()

Variant_Classification
Missense_Mutation         39472
Silent                    14792
3'UTR                      3274
Nonsense_Mutation          3171
Intron                     1434
5'UTR                      1369
RNA                        1175
Splice_Site                1053
Frame_Shift_Del             691
Splice_Region               624
Frame_Shift_Ins             375
3'Flank                     252
5'Flank                     194
In_Frame_Del                184
Translation_Start_Site       39
Nonstop_Mutation             36
In_Frame_Ins                 26
Name: count, dtype: int64

In [19]:
primary_mutations["Variant_Type"].value_counts()

Variant_Type
SNP    66609
DEL     1074
INS      471
ONP        7
Name: count, dtype: int64

In [20]:
primary_mutations[
    ["Hugo_Symbol", "Variant_Classification", "Variant_Type"]
].drop_duplicates().head(20)

   Hugo_Symbol Variant_Classification Variant_Type
0        TACC2      Missense_Mutation          SNP
1      JAKMIP3                 Silent          SNP
2        PANX3      Missense_Mutation          SNP
3         SPI1      Missense_Mutation          SNP
4      NAALAD2      Missense_Mutation          SNP
5         FAT3                 Silent          SNP
6      MTERFD3      Missense_Mutation          SNP
7       BTBD11      Missense_Mutation          SNP
8         NOS1                  5'UTR          SNP
9      SLC2A14      Missense_Mutation          SNP
10      SLC2A3      Missense_Mutation          SNP
11        EML1      Missense_Mutation          SNP
12        MYH6                 Silent          SNP
13       AKAP6      Missense_Mutation          SNP
14       WDR72                 Silent          SNP
15       GNPTG                 Silent          SNP
16    MAPK8IP3      Missense_Mutation          SNP
17     SPATA22      Missense_Mutation          SNP
18       HOXB1      Missense_Mutation          SNP
19        TP53      Missense_Mutation          SNP

In [21]:
protein_altering_classes = [
    "Missense_Mutation",
    "Nonsense_Mutation",
    "Frame_Shift_Del",
    "Frame_Shift_Ins",
    "Splice_Site",
    "In_Frame_Del",
    "In_Frame_Ins",
    "Translation_Start_Site",
    "Nonstop_Mutation"
]

protein_altering_mutations = primary_mutations[
    primary_mutations["Variant_Classification"].isin(protein_altering_classes)
].copy()

print("Primary mutation rows before functional filtering:",
      primary_mutations.shape[0])

print("Protein-altering mutation rows:",
      protein_altering_mutations.shape[0])

print("Unique samples:",
      protein_altering_mutations["Tumor_Sample_Barcode"].nunique())

print("Unique genes:",
      protein_altering_mutations["Hugo_Symbol"].nunique())

Primary mutation rows before functional filtering: 68161
Protein-altering mutation rows: 45047
Unique samples: 386
Unique genes: 13909

In [22]:
protein_altering_mutations[
    "Variant_Classification"
].value_counts()

Variant_Classification
Missense_Mutation         39472
Nonsense_Mutation          3171
Splice_Site                1053
Frame_Shift_Del             691
Frame_Shift_Ins             375
In_Frame_Del                184
Translation_Start_Site       39
Nonstop_Mutation             36
In_Frame_Ins                 26
Name: count, dtype: int64

In [23]:
protein_altering_mutations[
    ["Hugo_Symbol", "Variant_Classification", "Tumor_Sample_Barcode"]
].head(10)

   Hugo_Symbol Variant_Classification Tumor_Sample_Barcode
0        TACC2      Missense_Mutation      TCGA-02-0003-01
2        PANX3      Missense_Mutation      TCGA-02-0003-01
3         SPI1      Missense_Mutation      TCGA-02-0003-01
4      NAALAD2      Missense_Mutation      TCGA-02-0003-01
6      MTERFD3      Missense_Mutation      TCGA-02-0003-01
7       BTBD11      Missense_Mutation      TCGA-02-0003-01
9      SLC2A14      Missense_Mutation      TCGA-02-0003-01
10      SLC2A3      Missense_Mutation      TCGA-02-0003-01
11        EML1      Missense_Mutation      TCGA-02-0003-01
13       AKAP6      Missense_Mutation      TCGA-02-0003-01

In [24]:
all_primary_mutation_samples = set(
    primary_mutations["Tumor_Sample_Barcode"]
)

protein_altering_samples = set(
    protein_altering_mutations["Tumor_Sample_Barcode"]
)

samples_without_protein_altering = (
    all_primary_mutation_samples - protein_altering_samples
)

print(
    "Samples with mutation records but no selected protein-altering mutations:",
    len(samples_without_protein_altering)
)

samples_without_protein_altering

Samples with mutation records but no selected protein-altering mutations: 2

{'TCGA-06-0165-01', 'TCGA-06-0167-01'}

In [25]:
primary_mutations[
    primary_mutations["Tumor_Sample_Barcode"].isin(
        samples_without_protein_altering
    )
][
    [
        "Tumor_Sample_Barcode",
        "Hugo_Symbol",
        "Variant_Classification"
    ]
].sort_values(
    ["Tumor_Sample_Barcode", "Variant_Classification"]
)

      Tumor_Sample_Barcode Hugo_Symbol Variant_Classification
2117       TCGA-06-0165-01        LCN6                  5'UTR
2116       TCGA-06-0165-01       GPR35                 Intron
65131      TCGA-06-0167-01       WDR75                  3'UTR
2162       TCGA-06-0167-01    ARHGEF25                 Intron
2163       TCGA-06-0167-01      MRPL10                 Silent
2164       TCGA-06-0167-01     RAD54L2                 Silent

In [26]:
mutation_matrix = (
    protein_altering_mutations
    .assign(mutated=1)
    .pivot_table(
        index="Tumor_Sample_Barcode",
        columns="Hugo_Symbol",
        values="mutated",
        aggfunc="max",
        fill_value=0
    )
)

print("Rows (samples):", mutation_matrix.shape[0])
print("Columns (genes):", mutation_matrix.shape[1])

Rows (samples): 386
Columns (genes): 13909

In [27]:
mutation_matrix.head()

Hugo_Symbol,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AACS,AADAC,AADACL2,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
Tumor_Sample_Barcode,,,,,,,,,,,,,,,,,,,,,
TCGA-02-0003-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCGA-02-0033-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCGA-02-0047-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCGA-02-0055-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCGA-02-2466-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
all_primary_samples = primary_clinical["Sample ID"].tolist()

mutation_matrix_all = mutation_matrix.reindex(
    all_primary_samples,
    fill_value=0
)

print("Rows after adding all primary samples:",
      mutation_matrix_all.shape[0])

print("Columns:",
      mutation_matrix_all.shape[1])

# Add back all primary patients, even if they have no protein-altering mutations.

Rows after adding all primary samples: 585
Columns: 13909

In [29]:
mutation_matrix_all.loc[
    ["TCGA-06-0165-01", "TCGA-06-0167-01"]
].sum(axis=1)

Tumor_Sample_Barcode
TCGA-06-0165-01    0
TCGA-06-0167-01    0
dtype: int64

In [30]:
zero_mutation_samples = (
    mutation_matrix_all.sum(axis=1) == 0
)

print("Samples with zero selected protein-altering mutations:",
      zero_mutation_samples.sum())

Samples with zero selected protein-altering mutations: 199

In [31]:
from pathlib import Path

sequenced_path = Path(
    "../data/raw/gbm_tcga_pan_can_atlas_2018_cases_sequenced.txt"
)

print("Exists:", sequenced_path.exists())

Exists: True

In [32]:
lines = sequenced_path.read_text().splitlines()

for line in lines[:6]:
    print(line[:300])

cancer_study_identifier: gbm_tcga_pan_can_atlas_2018
stable_id: gbm_tcga_pan_can_atlas_2018_sequenced
case_list_name: Samples with mutation data
case_list_description: Samples with mutation data (397 samples)
case_list_category: all_cases_with_mutation_data
case_list_ids: TCGA-06-0881-01	TCGA-27-1833-01	TCGA-27-1832-01	TCGA-27-1831-01	TCGA-14-1043-01	TCGA-74-6577-01	TCGA-28-5218-01	TCGA-14-0786-01	TCGA-06-0238-01	TCGA-06-0125-01	TCGA-14-1795-01	TCGA-06-0125-02	TCGA-06-0174-01	TCGA-26-A7UX-01	TCGA-06-0216-01	TCGA-06-0171-01	TCGA-06-A7TL-01	TCGA-19-1787-

In [33]:
case_ids_line = next(
    line for line in lines
    if line.startswith("case_list_ids:")
)

sequenced_sample_ids = set(
    case_ids_line.split(":", 1)[1].strip().split("\t")
)

print("Official mutation-profiled samples:",
      len(sequenced_sample_ids))

Official mutation-profiled samples: 397

In [34]:
primary_sample_ids = set(primary_clinical["Sample ID"])

sequenced_primary_ids = (
    sequenced_sample_ids & primary_sample_ids
)

sequenced_not_primary = (
    sequenced_sample_ids - primary_sample_ids
)

print("Sequenced primary samples:",
      len(sequenced_primary_ids))

print("Sequenced samples not in primary cohort:",
      len(sequenced_not_primary))

sequenced_not_primary

Sequenced primary samples: 390
Sequenced samples not in primary cohort: 7

{'TCGA-06-0125-02',
 'TCGA-06-0171-02',
 'TCGA-06-0190-02',
 'TCGA-06-0210-02',
 'TCGA-06-0211-02',
 'TCGA-06-0221-02',
 'TCGA-14-1034-02'}

In [35]:
primary_mutation_record_ids = (
    mutation_sample_ids & primary_sample_ids
)

profiled_without_mutation_records = (
    sequenced_primary_ids - primary_mutation_record_ids
)

print(
    "Profiled primary samples with no mutation rows:",
    len(profiled_without_mutation_records)
)

profiled_without_mutation_records

Profiled primary samples with no mutation rows: 2

{'TCGA-06-0138-01', 'TCGA-06-0178-01'}

In [36]:
profiled_without_selected_mutations = (
    sequenced_primary_ids - protein_altering_samples
)

print(
    "Profiled primary samples with zero selected protein-altering mutations:",
    len(profiled_without_selected_mutations)
)

profiled_without_selected_mutations

Profiled primary samples with zero selected protein-altering mutations: 4

{'TCGA-06-0138-01', 'TCGA-06-0165-01', 'TCGA-06-0167-01', 'TCGA-06-0178-01'}

In [37]:
mutation_matrix_profiled = mutation_matrix.reindex(
    sorted(sequenced_primary_ids),
    fill_value=0
)

print("Rows (profiled primary samples):",
      mutation_matrix_profiled.shape[0])

print("Columns (genes):",
      mutation_matrix_profiled.shape[1])

Rows (profiled primary samples): 390
Columns (genes): 13909

In [40]:
zero_profiled_rows = (
    mutation_matrix_profiled.sum(axis=1) == 0
)

print(
    "Profiled primary samples with zero selected protein-altering mutations:",
    zero_profiled_rows.sum()
)
mutation_matrix_profiled.index[
    zero_profiled_rows
].tolist()

Profiled primary samples with zero selected protein-altering mutations: 4

['TCGA-06-0138-01', 'TCGA-06-0165-01', 'TCGA-06-0167-01', 'TCGA-06-0178-01']

In [41]:
from pathlib import Path

mutation_matrix_path = Path(
    "../data/processed/gbm_primary_profiled_mutation_matrix.tsv"
)

mutation_matrix_profiled.to_csv(
    mutation_matrix_path,
    sep="\t",
    index=True
)

print("Saved:", mutation_matrix_path)
print("Exists:", mutation_matrix_path.exists())

Saved: ..\data\processed\gbm_primary_profiled_mutation_matrix.tsv
Exists: True

In [45]:
mutation_matrix_check = pd.read_csv(
    mutation_matrix_path,
    sep="\t",
    index_col=0
)

print("Reloaded shape:", mutation_matrix_check.shape)

unique_values = pd.unique(
    mutation_matrix_check.values.ravel()
)

print("Unique matrix values:", sorted(unique_values))

mutation_matrix_check.loc[
    [
        "TCGA-06-0138-01",
        "TCGA-06-0165-01",
        "TCGA-06-0167-01",
        "TCGA-06-0178-01"
    ]
].sum(axis=1)

Reloaded shape: (390, 13909)
Unique matrix values: [np.int64(0), np.int64(1)]

Tumor_Sample_Barcode
TCGA-06-0138-01    0
TCGA-06-0165-01    0
TCGA-06-0167-01    0
TCGA-06-0178-01    0
dtype: int64