In [1]:
import pandas as pd
from pathlib import Path

expression_path = Path(
    "../data/raw/gbm_tcga_pan_can_atlas_2018_mrna_rsem.txt"
)

print("Exists:", expression_path.exists())

Exists: True

In [2]:
expression = pd.read_csv(
    expression_path,
    sep="\t",
    low_memory=False
)

print("Rows:", expression.shape[0])
print("Columns:", expression.shape[1])

Rows: 20531
Columns: 162

In [3]:
expression.columns.tolist()[:20]

['Hugo_Symbol',
 'Entrez_Gene_Id',
 'TCGA-02-0047-01',
 'TCGA-02-0055-01',
 'TCGA-02-2483-01',
 'TCGA-02-2485-01',
 'TCGA-02-2486-01',
 'TCGA-06-0125-01',
 'TCGA-06-0125-02',
 'TCGA-06-0129-01',
 'TCGA-06-0130-01',
 'TCGA-06-0132-01',
 'TCGA-06-0138-01',
 'TCGA-06-0141-01',
 'TCGA-06-0157-01',
 'TCGA-06-0158-01',
 'TCGA-06-0168-01',
 'TCGA-06-0171-02',
 'TCGA-06-0174-01',
 'TCGA-06-0178-01']

In [4]:
expression.head()

,Hugo_Symbol,Entrez_Gene_Id,TCGA-02-0047-01,TCGA-02-0055-01,TCGA-02-2483-01,TCGA-02-2485-01,TCGA-02-2486-01,TCGA-06-0125-01,TCGA-06-0125-02,TCGA-06-0129-01,...,TCGA-41-3915-01,TCGA-41-4097-01,TCGA-41-5651-01,TCGA-76-4925-01,TCGA-76-4926-01,TCGA-76-4927-01,TCGA-76-4928-01,TCGA-76-4929-01,TCGA-76-4931-01,TCGA-76-4932-01
0,NaN,100130426,0.0000,0.0000,0.0000,0.0000,0.0000,0.4604,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,NaN,100133144,3.0732,0.0000,2.9467,15.9952,5.5610,9.9246,3.3758,22.3207,...,8.2279,15.2648,1.2190,12.2160,9.5716,2.4096,10.1709,8.4757,6.1600,0.0000
2,UBE2Q2P2,100134869,6.7611,15.6973,13.9398,14.9571,4.8049,11.6684,3.3862,16.8239,...,10.2174,13.8987,10.3611,17.3596,13.9689,6.4257,6.4812,3.2496,7.9576,9.9502
3,HMGB1P1,10357,54.7036,31.3945,60.3441,91.8238,62.5366,52.1491,41.6125,76.2289,...,35.5731,27.6285,70.0838,108.1350,70.5556,43.0201,42.4584,62.2278,58.8188,60.1990
4,NaN,10431,886.3210,885.7740,1234.8300,470.0000,546.3410,391.9330,419.2460,642.3830,...,512.5160,593.2460,507.6950,531.9330,588.0410,620.8840,533.7420,668.9000,458.3530,499.5020

In [5]:
expression.iloc[:, :8].head(10)

,Hugo_Symbol,Entrez_Gene_Id,TCGA-02-0047-01,TCGA-02-0055-01,TCGA-02-2483-01,TCGA-02-2485-01,TCGA-02-2486-01,TCGA-06-0125-01
0,NaN,100130426,0.0000,0.0000,0.0000,0.0000,0.0000,0.4604
1,NaN,100133144,3.0732,0.0000,2.9467,15.9952,5.5610,9.9246
2,UBE2Q2P2,100134869,6.7611,15.6973,13.9398,14.9571,4.8049,11.6684
3,HMGB1P1,10357,54.7036,31.3945,60.3441,91.8238,62.5366,52.1491
4,NaN,10431,886.3210,885.7740,1234.8300,470.0000,546.3410,391.9330
5,NaN,136542,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
6,NaN,155060,232.9510,162.0180,135.0920,417.6190,276.2190,748.4210
7,RNU12-2P,26823,0.0000,0.5606,0.0000,1.9048,0.0000,1.6297
8,SSX9P,280660,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
9,NaN,317712,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [6]:
expression_sample_ids = set(expression.columns[2:])

print("Expression samples:", len(expression_sample_ids))

Expression samples: 160

In [8]:
clinical_path = Path("../data/processed/gbm_primary_clinical.tsv")

primary_clinical = pd.read_csv(
    clinical_path,
    sep="\t"
)

primary_sample_ids = set(primary_clinical["Sample ID"])

expression_primary_ids = (
    expression_sample_ids & primary_sample_ids
)

expression_not_primary = (
    expression_sample_ids - primary_sample_ids
)

print("Expression primary samples:",
      len(expression_primary_ids))

print("Expression samples not in primary cohort:",
      len(expression_not_primary))

expression_not_primary

Expression primary samples: 153
Expression samples not in primary cohort: 7

{'TCGA-06-0125-02',
 'TCGA-06-0171-02',
 'TCGA-06-0190-02',
 'TCGA-06-0210-02',
 'TCGA-06-0211-02',
 'TCGA-06-0221-02',
 'TCGA-14-1034-02'}

In [9]:
sequenced_path = Path(
    "../data/raw/gbm_tcga_pan_can_atlas_2018_cases_sequenced.txt"
)

lines = sequenced_path.read_text().splitlines()

case_ids_line = next(
    line for line in lines
    if line.startswith("case_list_ids:")
)

sequenced_sample_ids = set(
    case_ids_line.split(":", 1)[1].strip().split("\t")
)

sequenced_primary_ids = (
    sequenced_sample_ids & primary_sample_ids
)

print("Mutation-profiled primary samples:",
      len(sequenced_primary_ids))

Mutation-profiled primary samples: 390

In [10]:
# calculate the overlap
multiomics_primary_ids = (
    expression_primary_ids & sequenced_primary_ids
)

print(
    "Primary samples with BOTH expression and mutation profiling:",
    len(multiomics_primary_ids)
)

Primary samples with BOTH expression and mutation profiling: 152

In [12]:
# check which expression-primary samples are missing mutation profiling
expression_without_mutation_profile = (
    expression_primary_ids - sequenced_primary_ids
)

print(
    "Primary expression samples without mutation profiling:",
    len(expression_without_mutation_profile)
)

expression_without_mutation_profile

Primary expression samples without mutation profiling: 1

{'TCGA-15-1444-01'}

In [13]:
multiomics_primary_ids = sorted(multiomics_primary_ids)

print("Multi-omics samples:", len(multiomics_primary_ids))
print(multiomics_primary_ids[:10])

Multi-omics samples: 152
['TCGA-02-0047-01', 'TCGA-02-0055-01', 'TCGA-02-2483-01', 'TCGA-02-2485-01', 'TCGA-02-2486-01', 'TCGA-06-0125-01', 'TCGA-06-0129-01', 'TCGA-06-0130-01', 'TCGA-06-0132-01', 'TCGA-06-0138-01']

In [14]:
expression_multiomics = expression[
    ["Hugo_Symbol", "Entrez_Gene_Id"] + multiomics_primary_ids
].copy()

print("Rows (genes):", expression_multiomics.shape[0])
print("Columns total:", expression_multiomics.shape[1])
print(
    "Expression sample columns:",
    expression_multiomics.shape[1] - 2
)

Rows (genes): 20531
Columns total: 154
Expression sample columns: 152

In [17]:
recurrent_expression_columns = [
    col for col in expression_multiomics.columns
    if col.startswith("TCGA-") and col.endswith("-02")
]

print("Recurrent samples remaining:",
      len(recurrent_expression_columns))

recurrent_expression_columns

expression_multiomics.iloc[:, :8].head()

Recurrent samples remaining: 0

,Hugo_Symbol,Entrez_Gene_Id,TCGA-02-0047-01,TCGA-02-0055-01,TCGA-02-2483-01,TCGA-02-2485-01,TCGA-02-2486-01,TCGA-06-0125-01
0,NaN,100130426,0.0000,0.0000,0.0000,0.0000,0.0000,0.4604
1,NaN,100133144,3.0732,0.0000,2.9467,15.9952,5.5610,9.9246
2,UBE2Q2P2,100134869,6.7611,15.6973,13.9398,14.9571,4.8049,11.6684
3,HMGB1P1,10357,54.7036,31.3945,60.3441,91.8238,62.5366,52.1491
4,NaN,10431,886.3210,885.7740,1234.8300,470.0000,546.3410,391.9330

In [22]:
# Count missing gene symbols
missing_symbols = expression_multiomics["Hugo_Symbol"].isna().sum()

print("Rows with missing Hugo_Symbol:", missing_symbols)

# Check duplicate Hugo gene symbols
non_missing_symbols = expression_multiomics[
    "Hugo_Symbol"
].dropna()

print(
    "Unique non-missing Hugo symbols:",
    non_missing_symbols.nunique()
)

print(
    "Duplicated Hugo symbol rows:",
    non_missing_symbols.duplicated().sum()
)

# Check Entrez gene IDs
print(
    "Missing Entrez Gene IDs:",
    expression_multiomics["Entrez_Gene_Id"].isna().sum()
)

print(
    "Unique Entrez Gene IDs:",
    expression_multiomics["Entrez_Gene_Id"].nunique()
)

print(
    "Duplicated Entrez Gene ID rows:",
    expression_multiomics["Entrez_Gene_Id"].duplicated().sum()
)

# Check missing expression values
expression_values = expression_multiomics[
    multiomics_primary_ids
]
print(
    "Total missing expression values:",
    expression_values.isna().sum().sum()
)
print(
    "Genes containing at least one missing value:",
    expression_values.isna().any(axis=1).sum()
)

print(
    "Samples containing at least one missing value:",
    expression_values.isna().any(axis=0).sum()
)

Rows with missing Hugo_Symbol: 13
Unique non-missing Hugo symbols: 20511
Duplicated Hugo symbol rows: 7
Missing Entrez Gene IDs: 0
Unique Entrez Gene IDs: 20505
Duplicated Entrez Gene ID rows: 26
Total missing expression values: 0
Genes containing at least one missing value: 0
Samples containing at least one missing value: 0

In [23]:
missing_symbol_rows = expression_multiomics[
    expression_multiomics["Hugo_Symbol"].isna()
]

missing_symbol_rows[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
]

duplicated_symbols = expression_multiomics[
    expression_multiomics["Hugo_Symbol"].notna()
    & expression_multiomics["Hugo_Symbol"].duplicated(keep=False)
].sort_values("Hugo_Symbol")

duplicated_symbols[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
]

duplicated_entrez = expression_multiomics[
    expression_multiomics["Entrez_Gene_Id"].duplicated(keep=False)
].sort_values("Entrez_Gene_Id")

duplicated_entrez[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
]

print("Rows with missing symbols:", len(missing_symbol_rows))
print("Rows involved in duplicated Hugo symbols:", len(duplicated_symbols))
print("Rows involved in duplicated Entrez IDs:", len(duplicated_entrez))

Rows with missing symbols: 13
Rows involved in duplicated Hugo symbols: 14
Rows involved in duplicated Entrez IDs: 50

In [24]:
missing_symbol_rows[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
].to_string(index=False)

duplicated_symbols[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
].to_string(index=False)

duplicated_entrez[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
].to_string(index=False)

'Hugo_Symbol  Entrez_Gene_Id\n    C9orf47            1903\n      S1PR3            1903\n      FGF13            2258\n      FGF13            2258\n NCRNA00201            3192\n     HNRNPU            3192\n     CTAGE5            4253\n       MIA2            4253\n      SEPT4            5414\n   C17orf47            5414\n  C10orf113           10529\n       NEBL           10529\n  LOC283174           22997\n     IGSF9B           22997\n      MACF1           23499\n   KIAA0754           23499\n      DGCR9           26220\n     DGCR10           26220\n      DGCR5           26220\n     TMEM8B           51754\n     TMEM8B           51754\n     ELMOD1           55531\n     ELMOD1           55531\n      EHMT1           79813\n   FLJ40292           79813\n       LCOR           84458\n   C10orf12           84458\n     CXorf1           84631\n    SLITRK2           84631\n     SNAP47          116841\n     SNAP47          116841\n   ARHGAP42          143872\n    TMEM133          143872\n  C14orf139          161176\n   C14orf49          161176\n      BTBD8          284697\n   KIAA1107          284697\n     NKAIN3          286183\n     NKAIN3          286183\n     CC2D2B          387707\n  C10orf131          387707\n     MYO18A          399687\n      TIAF1          399687\n   C12orf74          440107\n    PLEKHG7          440107\n     CT45A4          441519\n     CT45A3          441519\n PALM2AKAP2          445815\nPALM2-AKAP2          445815\n PALM2AKAP2          445815'

In [27]:
missing_symbol_rows[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
].to_string(index=False)

duplicated_symbols[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
].to_string(index=False)

'Hugo_Symbol  Entrez_Gene_Id\n     ELMOD1           55531\n     ELMOD1           55531\n      FGF13            2258\n      FGF13            2258\n     NKAIN3          286183\n     NKAIN3          286183\n PALM2AKAP2          445815\n PALM2AKAP2          445815\n      QSOX1          200058\n      QSOX1            5768\n     SNAP47          116841\n     SNAP47          116841\n     TMEM8B           51754\n     TMEM8B           51754'

In [28]:
missing_symbol_rows[
    ["Hugo_Symbol", "Entrez_Gene_Id"]
].to_string(index=False)

'Hugo_Symbol  Entrez_Gene_Id\n        NaN       100130426\n        NaN       100133144\n        NaN           10431\n        NaN          136542\n        NaN          155060\n        NaN          317712\n        NaN          391343\n        NaN          553137\n        NaN           57714\n        NaN          645851\n        NaN          652919\n        NaN          728603\n        NaN          729884'

In [29]:
duplicate_symbol_summary = []

for symbol, group in expression_multiomics[
    expression_multiomics["Hugo_Symbol"].notna()
].groupby("Hugo_Symbol"):

    if len(group) > 1:
        values = group[multiomics_primary_ids]

        all_expression_identical = (
            values.nunique(axis=0, dropna=False) <= 1
        ).all()

        duplicate_symbol_summary.append({
            "Hugo_Symbol": symbol,
            "Rows": len(group),
            "Entrez_IDs": group["Entrez_Gene_Id"].tolist(),
            "Expression_identical": all_expression_identical
        })

duplicate_symbol_summary = pd.DataFrame(
    duplicate_symbol_summary
)

duplicate_symbol_summary

  Hugo_Symbol  Rows        Entrez_IDs  Expression_identical
0      ELMOD1     2    [55531, 55531]                 False
1       FGF13     2      [2258, 2258]                 False
2      NKAIN3     2  [286183, 286183]                 False
3  PALM2AKAP2     2  [445815, 445815]                 False
4       QSOX1     2    [200058, 5768]                 False
5      SNAP47     2  [116841, 116841]                 False
6      TMEM8B     2    [51754, 51754]                 False

In [30]:
duplicate_entrez_summary = []

for entrez_id, group in expression_multiomics.groupby(
    "Entrez_Gene_Id"
):

    if len(group) > 1:
        values = group[multiomics_primary_ids]

        all_expression_identical = (
            values.nunique(axis=0, dropna=False) <= 1
        ).all()

        duplicate_entrez_summary.append({
            "Entrez_Gene_Id": entrez_id,
            "Rows": len(group),
            "Hugo_Symbols": group["Hugo_Symbol"].tolist(),
            "Expression_identical": all_expression_identical
        })

duplicate_entrez_summary = pd.DataFrame(
    duplicate_entrez_summary
)

duplicate_entrez_summary

,Entrez_Gene_Id,Rows,Hugo_Symbols,Expression_identical
0,1903,2,"[C9orf47, S1PR3]",False
1,2258,2,"[FGF13, FGF13]",False
2,3192,2,"[HNRNPU, NCRNA00201]",False
3,4253,2,"[CTAGE5, MIA2]",False
4,5414,2,"[C17orf47, SEPT4]",False
5,10529,2,"[C10orf113, NEBL]",False
6,22997,2,"[IGSF9B, LOC283174]",False
7,23499,2,"[KIAA0754, MACF1]",False
8,26220,3,"[DGCR10, DGCR5, DGCR9]",False
9,51754,2,"[TMEM8B, TMEM8B]",False
10,55531,2,"[ELMOD1, ELMOD1]",False
11,79813,2,"[EHMT1, FLJ40292]",False
12,84458,2,"[C10orf12, LCOR]",False
13,84631,2,"[CXorf1, SLITRK2]",False
14,116841,2,"[SNAP47, SNAP47]",False
15,143872,2,"[ARHGAP42, TMEM133]",False
16,161176,2,"[C14orf139, C14orf49]",False
17,284697,2,"[BTBD8, KIAA1107]",False
18,286183,2,"[NKAIN3, NKAIN3]",False
19,387707,2,"[C10orf131, CC2D2B]",False
20,399687,2,"[MYO18A, TIAF1]",False
21,440107,2,"[C12orf74, PLEKHG7]",False
22,441519,2,"[CT45A3, CT45A4]",False
23,445815,3,"[PALM2AKAP2, PALM2AKAP2, PALM2-AKAP2]",False

In [31]:
print(
    "Duplicate Hugo groups:",
    len(duplicate_symbol_summary)
)

print(
    "Hugo groups with identical expression:",
    duplicate_symbol_summary["Expression_identical"].sum()
)

print(
    "Duplicate Entrez groups:",
    len(duplicate_entrez_summary)
)

print(
    "Entrez groups with identical expression:",
    duplicate_entrez_summary["Expression_identical"].sum()
)

Duplicate Hugo groups: 7
Hugo groups with identical expression: 0
Duplicate Entrez groups: 24
Entrez groups with identical expression: 0